name: Deploy Streamlit App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install system dependencies on Ubuntu
      if: matrix.os == 'ubuntu-latest'
      run: |
        while IFS= read -r package; do
          sudo apt-get install -y "$package"
        done < packages.txt
      shell: bash

    - name: Install system dependencies on macOS
      if: matrix.os == 'macos-latest'
      run: |
        brew update
        while IFS= read -r package; do
          brew install "$package"
        done < packages.txt
      shell: bash

    - name: Install system dependencies on Windows
      if: matrix.os == 'windows-latest'
      run: |
        choco install packages.config
      shell: powershell

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Create Streamlit config directory
      run: |
        mkdir -p ~/.streamlit/
      shell: bash

    - name: Add secrets.toml
      run: |
        echo "${{ secrets.SECRETS_TOML }}" > ~/.streamlit/secrets.toml

    - name: Run Streamlit
      run: |
        streamlit run your_streamlit_script.py
      shell: bash
