name: Deploy Streamlit App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y $(cat packages.txt)
      shell: bash

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Create Streamlit config directory
      run: |
        mkdir -p ~/.streamlit/
      shell: bash

    - name: Add secrets.toml
      run: |
        echo "${{ secrets.SECRETS_TOML }}" > ~/.streamlit/secrets.toml

    - name: Set TESSDATA_PREFIX environment variable
      run: echo "TESSDATA_PREFIX=/usr/share/tesseract-ocr/4.00/" >> $GITHUB_ENV

    - name: Run Streamlit
      run: |
        streamlit run your_streamlit_script.py
      shell: bash
